### ISSUE TITLE
revm error handling

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#136]
We want to be better about our error handling when interacting with revm. We encountered an error when trying to deploy portfolio regarding the contract size but were unsure why until @Autoparallel added the following lines to propagate the error for us. 

https://github.com/primitivefinance/arbiter/blob/0e90313fc2caeb31839cdd0d4c4c5a10762563fb/crates/simulate/src/execution.rs#L95-L99

**Comment by 0xJepsen** [comment]
We want to identify and create issues on all revm components to propagate logs and errors.

**Comment by Autoparallel** [comment]
Redundant
