### ISSUE TITLE
Create `Manager` struct that uses `Agent` as trait

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#138]
- [ ] Create `SimulationManager` struct that uses `Agent` as trait
- [ ] Give `Manager` methods `deploy` and `mint`

**Comment by 0xJepsen** [comment]
This seams good to me. Can we maybe call it something a little more descriptive than manager? like `admin_agent`

**Comment by Autoparallel** [comment]
Yeah, we can call it `admin`. At one point I thought about calling this agent `god` or `omniscient`.

**Comment by 0xJepsen** [comment]
lol im down with those except omniscient is hard to spell
