### ISSUE TITLE
Agent Type: SimpleArbitrageur 

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#144]
In the `/arbiter/crates/simulate/src/` directory, implement an `SimpleArbitrageur` module/struct.
- [x] Consume and monitor events #142 

`SimpleArbitrageur`:

- [x] The `SimpleArbitrageur` struct has filters and stores prices.
- [x] Spawn a thread that listens for events that match the filters.
- [x] Compute the price differences between each pool after each price change and store them.
- [x] When the prices are detected to be different, exit the thread.

**Comment by 0xJepsen** [comment]
Looking at the structure. Lets tackle this next. We can put it in the agent module.

**Comment by Autoparallel** [comment]
I can think of some ways we can accomplish this. Let me outline an idea for a `SimpleArbitrageur`:

- [ ] The `SimpleArbitrageur` struct should have two pools/exchanges (addresses, properties) and store their current prices.
- [ ] Spawn two threads that listen to prices on each pool. As each price changes, record the new prices.
- [ ] Compute the price differences between each pool after each price change and determine if this difference surpasses the no-arbitrage bounds.
- [ ] When a large enough price is detected, compute the optimal arbitrage quantity.
- [ ] Build and execute two transactions to capture the arb.
- [ ] Store the information over execution history so we can record the simulation.
