### ISSUE TITLE
Agent Type: Retailer

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#145]
In the `/arbiter/crates/simulate/src/` directory, implement an Retailer trait for agents.

**Comment by Autoparallel** [comment]
`Retailer` can be a struct that implements the `Agent` trait. We can have a retailer behave stochastically. I will look into some models to use here.

**Comment by Autoparallel** [comment]
Looks like using a gamma process would be a good start to the temporal behavior of an agent like a retailer. 

> If you have a random number generator that can draw from a gamma distribution with appropriate rate and shape parameters, then you can use it to generate a sequence of waiting times between trades. Specifically, you would draw from the gamma distribution to determine the time between the current trade and the next trade. Then, you would wait for that amount of time before making the next trade.

**Comment by 0xJepsen** [comment]
I like the initial approach with the gamma process. I like the idea of using ML in the future for this but not sure how feasible it is vs how much it would improve the model.

**Comment by Autoparallel** [comment]
This I'll take once we get our first simulations done.
