### ISSUE TITLE
Agent Type: Market Maker

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#146]
In the /arbiter/crates/simulate/src/ directory, implement an Market Maker trait for agents.

**Comment by Autoparallel** [comment]
Market maker is probably just for DEXs like UniV3 but... maybe not?

**Comment by 0xEstelle** [comment]
> Market maker is probably just for DEXs like UniV3 but... maybe not?

yes and no. similar behaviours could def exist between any set of more than 1 cfmm. dk about within 1 cfmm.

**Comment by Autoparallel** [comment]
We should meet about this one and discuss details further.
