### ISSUE TITLE
Simulation Property: Time

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#147]
Implement a Poisson Process for the agents to model trade frequencies. Poisson processes are traditionally used for modeling random variables. 

Note: needs to be in line with [Portfolio](https://github.com/primitivefinance/portfolio) and it's notion of time. 

- How often do they trade (poisson process)

**Comment by Autoparallel** [comment]
I plan to get to this after we do simulations with static pools.

**Comment by Autoparallel** [comment]
I did find that we have access to `evm.env.block.timestamp` in the `environment.rs`. This could be useful.

**Comment by 0xJepsen** [comment]
Closing in favor of using s DES like Aika or sim-rs
