### ISSUE TITLE
Initialize and outline a Mdbook to document the project

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#169]
This is a great first issue and a good way to get familiar with the contract architecture. The way that i would approach this is in two steps. [Mdbook](https://github.com/rust-lang/mdBook) is a rust native documentation approach. 

- [ ] Outline a few core chapters
- [ ] Brainstorm big picture structure. 
- [ ] Brainstorm content for MVP (it doesn't have to be complete but goal is to put it in a good place that someone else can expand on. 
- [ ] Make a Pr with initial outline and content

**Comment by Autoparallel** [comment]
We don't need this yet so I'm iceboxing it.

**Comment by 0xJepsen** [comment]
Maybe now that we are starting to draft a 'How To' we can start to open this up.
