### ISSUE TITLE
Integrate `folio` for communicating with Portfolio contracts.

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#210]
@ts0yu created a compiler that allows us to compile the bytecode necessary for the `multiprocess` of the Portfolio contracts. This will be useful for us as we test and deploy Portfolio specifically. [Here is a link to the repo.](https://github.com/ts0yu/folio)

This will need to work similarly to our typical flow for calling contracts which amounts to

```
let call_data = token_x.encode_function("balanceOf", recast_address(user_address))?;
let execution_result = alice.call_contract(&mut manager.environment, &token_x, call_data, Uint::from(0)); 
```

Something like:

```
let call_data = folio.encode_instructions("createPool", args);
let execution_result = alice.call_contract(&mut manager.environment, &portfolio, call_data, Uint::from(0));
```

would be nice.

(I need to look deeper into the `folio` repo before I can add more detail here.)

Waylons Task List:
- [x] Ensure Bit parity with the create_pair opcode
- [ ] Figure out the create_pool opcode encoding

**Comment by Autoparallel** [comment]
@0xJepsen @Alexangelj what do we think the status is on this?

**Comment by 0xJepsen** [comment]
Going to close this due to the new contracts using multicall
