### ISSUE TITLE
Abstract functionality out of main.

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#214]
We should make all of the functionality in main as simple as possible so that it is just `clap`.  For example, for `sim` we have this snippet:

```
async fn main() -> Result<(), Box<dyn Error>> {
    let args = Args::parse();

    match &args.command {
        Some(Commands::Sim { config: _ }) => {
            sim::sim()?;
        }
 }
 ```
 
 This will let us grow the `cli` handling without making main unbelievably large. For each leg of the `match &args.command`, make each a single line command like `sim::sim()?`. 
 
 - [x] Move the logic for `chain` out of `main.rs` and into `chain.rs`.
 - [x] Move the logic of `gbm` out of `main.rs` and into `gbm.rs`.
 - [x] Move the logic of `ou` out of `main.rs` and into `ou.rs`.

**Comment by Autoparallel** [comment]
@0xEstelle I think you can take care of the tasks 2 and 3 here with your branch.

**Comment by 0xEstelle** [comment]
Def can!! Currently i have all the price processes defined in one file price_process.rs. are you thinking of isolating one each to its own file?

**Comment by 0xEstelle** [comment]
done
