### ISSUE TITLE
Can we use `ContractCalls` enums in bindings in `SimulationContract`?

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#215]
I noticed that the bindings have an enum for all the calls (and events) that can be made to the contract. This could be helpful for encoding/decoding. E.g.,

```
    pub enum LiquidExchangeCalls {
        Admin(AdminCall),
        ArbiterTokenX(ArbiterTokenXCall),
        ArbiterTokenY(ArbiterTokenYCall),
        Price(PriceCall),
        SetPrice(SetPriceCall),
        Swap(SwapCall),
    }
```

Food for thought.

**Comment by 0xJepsen** [comment]
I think this could be a nice quality of life thing, however not sure what the priority should be.

**Comment by Autoparallel** [comment]
I iceboxed it.

**Comment by 0xJepsen** [comment]
Closed in favor of middleware
