### ISSUE TITLE
Adding Staked ETH ("stETH") to Arbiter

### ISSUE THREAD

**Issue by eljhfx** [primitivefinance/arbiter#22]
Looks Great I Added some tasks for the issue. 
- [x] Within `token/mod.rs`, add the desired token information consisting of `name`, `decimals`, `address`, and `is_stable`.
- [x] Insert the token into the hashmap below.

**Comment by 0xJepsen** [comment]
I think this is great! Maybe consider adding the Rocket Pool ETH `rETH` as well?
- [ ] Within `token/mod.rs`, add the desired token information consisting of `name`, `decimals`, `address`, and `is_stable`.
- [ ] Insert the token into the hashmap below.

**Comment by eljhfx** [comment]
> I think this is great! Maybe consider adding the Rocket Pool ETH `rETH` as well?

roger that

**Comment by eljhfx** [comment]
> Looks Great I Added some tasks for the issue.
> 
> * [ ]  Within `token/mod.rs`, add the desired token information consisting of `name`, `decimals`, `address`, and `is_stable`.
> * [ ]  Insert the token into the hashmap below.

also thanks for the description. probably would've been lost w/ out the file paths

**Comment by eljhfx** [comment]
what is the isstable field for?

**Comment by ColinPR** [comment]
> what is the is_stable field for? (assuming it refers to stable coin)

Yes. This is a tag for stable coins. Users will likely decide to price their assets in terms of stable tokens. Some pools (e.g., Balancer) treat stable tokens differently.
