### ISSUE TITLE
Get rid of need to `.get()` from the `agents` HashMap constantly

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#229]
This is an obvious UX issue and will also be a slowdown since we will have to search the map each time we want to call a contract or deploy. There's got to be a nice way to get rid of this issue with the borrow checker, but I'm not sure what it is yet.

**Comment by Autoparallel** [comment]
It might be possible to extract the struct inside the `AgentType` enum in some way and use that:

```rust
        let base_arbitrageur = match arbitrageur {
            AgentType::SimpleArbitrageur(base_arbitrageur) => base_arbitrageur,
            _ => panic!()
        };
        base_arbitrageur.detect_arbitrage();
```

**Comment by 0xJepsen** [comment]
Closed for now.
