### ISSUE TITLE
Implement objective functions for router

### ISSUE THREAD

**Issue by 0xEstelle** [primitivefinance/arbiter#232]
We need an objective function for every desired swap based action we wish to use the optimal router for. We can start with the following that were also implemented in the CFMMRouter.jl package:
- [ ] LinearNonnegative (this is the objective function for arbitrage trades)
- [ ] BasketLiquiditation (objective for liquidating a whole basket of assets for one asset)
- [ ] Swap (objective for swapping from one basket to another)

**Comment by Autoparallel** [comment]
@0xEstelle can you split these into smaller issues with a bit more information as you get around to it?
