### ISSUE TITLE
Add a code coverage badge to our README

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#233]
We want to get to high code coverage with our tests since Arbiter needs to be as bug free as possible. Let's add a badge to show how far along we are to 100% coverage.

**Comment by funkycadet** [comment]
Hello @Autoparallel I'd love to work on this issue. Can this be assigned to me?

**Comment by ts0yu** [comment]
done!

**Comment by funkycadet** [comment]
@ts0yu I'm done working on this. Here's the PR I opened for it: #258

Looking forward to a review

**Comment by ts0yu** [comment]
good stuff @funkycadet!!

**Comment by funkycadet** [comment]
Thanks man @ts0yu 🥂

**Comment by Autoparallel** [comment]
> Thanks man @ts0yu 🥂
> 
> 
> 
> Quick question: can you install codecov on this repository? I believe you have sufficient rights to be able to do that

I got this merged yesterday😃 and it looks great!

Did I miss anything?

**Comment by funkycadet** [comment]
Nothing much. Everything is great. I just realized that this repository should have codecov app enabled for it and the codecov token generated for it on codecov should be added to the repository as a secret. That's all.
