### ISSUE TITLE
Unit test for `GBM::generate()`

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#235]
Write a test in the `price_process.rs` file that does the following:

- [ ] Verifies that seeded randomness is correct, i.e., using the same seed does yield the same output and using a different seed yields a different output.
- [ ] Verifies that a single step is computed properly.

**Comment by 0xEstelle** [comment]
I can def do this one

**Comment by Autoparallel** [comment]
> I can def do this one

Good plan. Gives a community member a way to accomplish the other related issue for OU.

**Comment by 0xEstelle** [comment]
nice i like that
