### ISSUE TITLE
Modular Sims

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#239]
I think one thing we should do in our architecture is make a a simulation crate where we can have on going constructions on a collection of protocols like `portfolio`, `uniswap`, `curve`, etc. These will 
- Serve as an example of the power of arbiter to external contributors and projects
- Demonstrate economic risk auditing capabilities
- Give more opportunities from other core protocols to contribute

I think the best way in which we do this needs more discussion. My initial idea is that we change `sim.rs` to `portfolio_sim.rs` and then put it in a sims module where we have sims for major core protocols. I think the other sims will actually be much easier to build and design as well since portfolio has custom bit encoding for it's calls which introduce a lot of developer frictions and overhead. My open questions are:
- where in the code base should this module live? Right now the `sim.rs` file lives in `crates/cli/src/commands` maybe we make a `crates/cli/src/sims` directory for this to live in? What are the teams thoughts.

**Comment by Autoparallel** [comment]
A `sims` submodule in `cli` is a good idea. We'll also want to integrate some of the other issues up such as #211 so that sims can become more modular. If we can make an arbitrageur handle two `Exchange`s, then a lot can be abstracted away.

**Comment by 0xJepsen** [comment]
This is good because we will also be able to engage with other teams of these protocols which i think will be very high leverage

**Comment by Autoparallel** [comment]
An overhead issue at the moment is working with Vyper contracts *a-la* issue #222. We should consider tackling this in the mean time too.

**Comment by Autoparallel** [comment]
@0xJepsen can we consider moving this more broadly to a discussion and creating smaller issues off the discussion?

Right now I think it's a good issue to go ahead and introduce `sim` as a module with submodules therein.

**Comment by 0xJepsen** [comment]
Yes this sounds good to me!
