### ISSUE TITLE
feat: adjustable gas price

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#241]
# Idea

To make simulations as realistic as possible, we need to give agents some raw ether and force them to pay gas for transactions. At the moment, the gas price has been fixed to zero.

## Solution
We can set another parameter in `EnvironmentParameters` similar to how I commented on #418. We can have an enum, or something, that allows the user to choose some gas rules for the environment. They can be externalized, stochastic, or off, e.g.,:
```rust
pub enum GasRules {
     UserControlled,
     Randomized(f64),
     None(u128),
}
```
- `UserControlled`: will give the user the ability to make calls such as `client.set_gas_price()`.
- `Randomized`: would give the user gas price based on something like EIP-1559 rules. Could even play off of the `BlockType` enum I mentioned in #418. 
- `None`: The user would not change gas price ever and have it set to the internal `u128`.

This `GasRules` can go into the `EnvironmentParameters`.

We can also perhaps add functionality for gas tips later on if we expand upon an enum.

--- 

**IT IS WORTH NOTING THAT ISSUE #410 IS RELEVANT HERE TOO**

**Comment by Autoparallel** [comment]
I am going to work on this soon. I have thoughts on how to get a basic version of this done.

**Comment by 0xJepsen** [comment]
We could probably put this in an arbiter.toml that would maybe configure revm?
