### ISSUE TITLE
Fixing wsteth, wseth naming in tokens/mod.rs

### ISSUE THREAD

**Issue by eljhfx** [primitivefinance/arbiter#25]
Lines 140 and 141 call it wseth and everywhere else, it's wsteth. Feels like that was a mistake. Wdyt?

![Screen Shot 2022-11-23 at 8 43 11 PM](https://user-images.githubusercontent.com/56851203/203675448-5c61bcd2-0639-4663-8a00-703767f1cc4c.png)

_Originally posted by @eljhfx in https://github.com/primitivefinance/arbiter/discussions/24_

**Comment by eljhfx** [comment]
@0xJepsen happy to take this one sir

**Comment by eljhfx** [comment]
https://github.com/primitivefinance/arbiter/pull/28

**Comment by Autoparallel** [comment]
Closing issue. Newest updates in `main` branch have this fixed now.
