### ISSUE TITLE
Replace prints with logs

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#251]
Good practice for productions code

**Comment by Autoparallel** [comment]
Yeah this would be good. We can also change log verbosity level too right?

Where do we want to be printing logs?

**Comment by 0xJepsen** [comment]
I think in the zero -> production rust book they have some good information on this. But idk as of now.

**Comment by 0xJepsen** [comment]
Going to close this for now since things will change a ton with the next release. We can revisit later.
