### ISSUE TITLE
`SimulationEnvironment` middleware

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#263]
Using the contract bindings for our contracts is helpful, but we basically only use the ABI. The issue is that we can't really use the bindings for deployment since it will use the middleware to communicate to an JSON-RPC endpoint to do such a deployment. 

However, if we can construct a middleware for the `SimulationEnvironment` that would allow for bindings to properly deploy so that we could use the pre-generated function calls and what not, then we would be saving a lot of effort, increasing UX, and making the move from simulation to on-chain much more simple. 

I previously attempted to create a middleware, but it was extremely minimal and didn't prove to be of any use (see `middleware.rs` in the `simulate` crate). 

Perhaps we can make a channel that behaves like a JSON-RPC enough for further use of bindings and build a `SimulationMiddleware` around this.

**Comment by 0xJepsen** [comment]
Want to just link this here as i think it's pretty relevant 
https://github.com/gakonst/ethers-rs/issues/1405

**Comment by 0xJepsen** [comment]
Closing because we found [ethers-reth](https://github.com/SorellaLabs/ethers-reth)
