### ISSUE TITLE
Create SimpleArbitrageur for LiquidExchange <> Portfolio

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#264]
In the `portfolio_sim.rs` we need an arbitrageur that is going to properly arb the pools with the correct arb amounts. 

- [ ] Given a target price and the current pool price, compute the arbitrage amount.
- [ ] Use the auto-deployed math scripts for this.

**Comment by 0xEstelle** [comment]
I can help with this if youd like

**Comment by 0xEstelle** [comment]
We should just note here too btw, this issue is required to complete task 3 in issue #231
