### ISSUE TITLE
Create Token List Convention

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#27]
Our token list needs to follow a set format. This is important for our current tokens and more so the new tokens added by our community. 

@0xJepsen and I can review this.

**Comment by eljhfx** [comment]
Agreed, but I also think it should just be automated sooner than later

**Comment by Autoparallel** [comment]
@eljhfx any chance you want to try an automation for this?

**Comment by 0xJepsen** [comment]
This is closed by the macro that was made for this
