### ISSUE TITLE
InvalidInvariant on swaps

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#288]
When we call swaps (at least, more than one), we get an error back from the contract that is of `InvalidInvariant`. 

The error also should send back `int` but they are decoded into `uint` by `ethabi`. This is a problem.

**Comment by 0xJepsen** [comment]
Found one bug in the way we were initializing prices, but doesn't fix this.

**Comment by 0xJepsen** [comment]
so it seems there is an underflow?

**Comment by 0xJepsen** [comment]
Think this is still the current bug in #382

**Comment by 0xJepsen** [comment]
This is sim specific so going to close as it should be brought up here https://github.com/primitivefinance/proto-sim-portfolio if still present
