### ISSUE TITLE
Fix `compute_arb_size` bug in portfolio sim

### ISSUE THREAD

**Issue by 0xEstelle** [primitivefinance/arbiter#291]
There is a bug that only occurs in extremely rare cases (for price changes < +/- 1e-17 different) where the `arb_amount_y` variable yields a distinct value on the order of 1e5 that remains constant within the same neighbourhood of price changes. In a sense, it appears something is going on in the y calculation that causes it to pass a constant value out if the reference price and pool price are too close. It likely won't affect the majority of simulation runs but does indeed create a conditional environment where the function doesn't work.

**Comment by 0xJepsen** [comment]
Pretty sure this was closed with colins PR
