### ISSUE TITLE
Implement GBM price model

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#30]
It would be helpful for testing strategies and functionality if we implemented a Geometric Brownian Motion (GBM) price model. 

- Could be used as an external market for testing arbitrage.
- Could be used for testing performance of vault products.

**Comment by eljhfx** [comment]
Are you still working on this? Would love to help build the base classes.

**Comment by 0xJepsen** [comment]
It might be a good idea to break this down into smaller components if you like.

**Comment by Autoparallel** [comment]
Closing this issue due to #55 

Will create more issues related to this later on.
