### ISSUE TITLE
Accuracy bug in `uniswap::compute_arb_size()`

### ISSUE THREAD

**Issue by 0xEstelle** [primitivefinance/arbiter#301]
Currently the compute arb size seems to be accurate up to roughly +/-2.5*10^(-4) (meaning the pool price after arbitrage can vary up to this much from the target price) which cannot be explained by the arithmetic in the `compute_arb_size` function. The only known loss of accuracy occurs on the `sqrt` call, however,  this at worst affects 1e-9 accuracy. We need to figure out the source of this loss of accuracy.

**Comment by Autoparallel** [comment]
Is this still an issue @0xEstelle?

**Comment by 0xEstelle** [comment]
> Is this still an issue @0xEstelle?

Yea

**Comment by 0xJepsen** [comment]
@0xEstelle didn't we verify this is actually okay now?

**Comment by 0xEstelle** [comment]
Not that i am aware of

**Comment by 0xJepsen** [comment]
Closed as it is now simulation specific
