### ISSUE TITLE
Add a config.yaml for input arguments

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#33]
Right now, we have CLI arguments and we have environment arguments. I think that it would be best to implement inputs in a uniform way that is also a good experience.

I think the best way around this is to use CLI arguments with defaults but allow the user to load a `config.yaml` file. This would be the same set up as [Erigon](https://github.com/ledgerwatch/erigon). 

The main tasks are then:
- [x] Allow for a flag like `--config-file` where a user can provide a `config.yaml`. 
- [x] Set up a preconfigured `config.yaml` file.
- [x] Change API/RPC away from environment variables and into CLI configs.

---

What do you think? @0xJepsen  @eljhfx @ts0yu

**Comment by Autoparallel** [comment]
@0xJepsen Do you prefer a `config.toml`?

**Comment by ts0yu** [comment]
a .toml file might be a bit nicer

**Comment by 0xJepsen** [comment]
Let us do a toml then.

**Comment by ts0yu** [comment]
Task 1 is done https://github.com/primitivefinance/arbiter/pull/43
