### ISSUE TITLE
Create `revm` middleware

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#339]
For the longest time we wanted to figure out how to use `ether.rs` to create a provider object with a dummy client so we can use it the same way but without the excess overhead so we can submit to revm locally rather than to a client by default.  

recently we found this https://github.com/SorellaLabs/ethers-reth which I think is exactly what we want so we should look into integration with it.

**Comment by Autoparallel** [comment]
We also have a lot of the work already done. The latest changes in branch `colin/evm-tx-receiver` are going to be a start towards this.

**Comment by Autoparallel** [comment]
Redundant to #370
