### ISSUE TITLE
Add a store historical data configuration

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#36]
implement a local [Postgres DB](https://docs.rs/tokio-postgres/latest/tokio_postgres/) which monitors and stores indexed event information

**Comment by 0xJepsen** [comment]
Postgres might be a good idea. I was looking at https://github.com/flashbots/mev-inspect-rs, and they use it there. It could be a good reference.

**Comment by ts0yu** [comment]
i was also looking there. going to do some research on how best to represent the table then ill make a pr

**Comment by 0xJepsen** [comment]
I'm going to icebox this for the beta release
