### ISSUE TITLE
Implementing ethers middleware for Revm 

### ISSUE THREAD

**Issue by davebryson** [primitivefinance/arbiter#370]
I saw the comment here: https://github.com/primitivefinance/arbiter/blob/main/lib/simulate/src/environment/middleware.rs  about implementing a middleware approach and spent a bit of time trying to make it work (without success).  Middleware that can interact with SimulationEnvironment would be nice as you could use all of `ethers-rs` existing functionality (abigen, provider, etc...).  

However, I'm not sure this will work without adding more logic to SimulationEnvironment to handle the calls.  For example, `ethers::Provider middleware` is the last in the middleware chain and will always be called.  Some of the calls (as far as I can tell) can't be handled by a base implementation of Revm.  For example, see: [fill_transaction()](https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/rpc/provider.rs#L557) it expects to calculate eip1559 gas. 

Am I'm missing something here?  Or is the intention to extend `SimulationEnvironment` to support the above?

Thanks!

**Comment by 0xJepsen** [comment]
We have also been chatting with the Sorellus labs people who made [ethers-reth](https://github.com/SorellaLabs/ethers-reth) and learning from their implementation which is pretty fast.

**Comment by davebryson** [comment]
Thanks for the pointer to `ethers-reth`!  Looks very interesting.  They haven't tackled `send_transaction()` yet which is the one needed for contract writes.  I wonder if the additional complexity of adding what is needed to support middleware for Reth/Revm will be worth the trade off of just talking to an Anvil?

**Comment by 0xJepsen** [comment]
For arbiter 100% revm without anvil is like 200x speed up. You can use anvil but then you are kinda just the same as apeworkx

**Comment by Autoparallel** [comment]
> Thanks for the pointer to `ethers-reth`! Looks very interesting. They haven't tackled `send_transaction()` yet which is the one needed for contract writes. I wonder if the additional complexity of adding what is needed to support middleware for Reth/Revm will be worth the trade off of just talking to an Anvil?

`send_transaction()` shouldn't be too bad with an interface over `revm`. I might be crazy, but I will give this specific instance a shot today.

If you look at the latest PR #362, we now send txns via a channel to a running EVM instance. This should make middleware a bit more intuitive.
