### ISSUE TITLE
Scaffold out `Middleware`

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#372]
- [x] Get the necessary types for the `ethers::providers::Middleware` trait.
- [x] Get the necessary functions for the `ethers::providers::Middleware` trait.
- [x] Get the necessary imports.
- [x] Mark functions as `unimplemented!()` if we do not believe we need them (ever).
- [x] Mark functions as `todo!()` if we believe we need to implement them.

**Comment by 0xJepsen** [comment]
Nice this looks clean
