### ISSUE TITLE
publish arbiter lib to crates.io

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#385]
publish the arbiter library to crates.io

**Comment by Autoparallel** [comment]
Need a name for the lib first!

**Comment by 0xJepsen** [comment]
yep! I did some work this morning looking into the right steps. In order to publish the binary we have to publish the lib/crates too, I think we are talking a lot about this already with the architecture and middleware changes. Maybe we hold off on this until that refactor?
