### ISSUE TITLE
Implement `Middleware` for `RevmEnvironment`

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#401]
Ethers implements a specific case of `Middleware` for `Provider<M>`. It is built in such a way that uses `serde` to do serialization/deserialization to make raw JSON-RPC calls. Using this ourselves doesn't really make sense as we would just have to deserialize the JSON data and match against it in our `RevmEnvironment`. 

Instead we should just implement it ourselves and build `AgentMiddleware` or something with `RevmEnvironment` as an inner.

**Comment by davebryson** [comment]
@0xJepsen   You can check it out here: https://github.com/davebryson/revm-provider.  Still a work in progress but has the basic provider and contract interface

**Comment by davebryson** [comment]
@0xJepsen @Autoparallel   Not sure if this is useful to you or not, but I've created a customized version that auto-generates contract bindings that do not rely on `ethers provider` or `middleware`. Instead contracts talk directly to `revm`.  The API is nearly identical to `ethers` generated contracts and it supports extracting `events`.  [Here's an example](https://github.com/davebryson/revmup/tree/main#example)

**Comment by 0xJepsen** [comment]
Hey @davebryson this looks really clean. I think this is a great approach. Right now we are almost done with implementing the middleware trait for our architecture. However with the ethers.rs rewrite coming (Alloy) I think this will be really worth considering. Would you be open to meeting and we can discuss future developments? I would be really interested in hearing your feedback and desired functionality of arbiter.

**Comment by davebryson** [comment]
> Hey @davebryson this looks really clean. I think this is a great approach. Right now we are almost done with implementing the middleware trait for our architecture. However with the ethers.rs rewrite coming (Alloy) I think this will be really worth considering. Would you be open to meeting and we can discuss future developments? I would be really interested in hearing your feedback and desired functionality of arbiter.

Sounds good.  Yes, I'd love to meet and discuss more.
