### ISSUE TITLE
feat: add `value` option when sending transaction.

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/arbiter#410]
Lets us simulate functions that are `payable` in solidity and use ETH

**Comment by Autoparallel** [comment]
Is this closed by #378 @Alexangelj ?

**Comment by 0xJepsen** [comment]
This is closed with the new release. I have tested it.

**Comment by Alexangelj** [comment]
Can we reopen? I was looking at middleware and it looks like value is being set to zero always: https://github.com/primitivefinance/arbiter/blob/54018543c0b915ce84f9e799f1fcea3adedd9688/arbiter-core/src/middleware.rs#L283

I was also trying to make the changes for it to work but can't get a new contract binding in the codebase, since when i try to build/bind I run into that unicorn emoji error. I tried using ethers-solc to compile the contract and get the bytecode inline but that also didn't yield results, couldn't get it to working

I need a contract that has a payable function to test the functionality in arbiter

**Comment by 0xJepsen** [comment]
I think it defaults to zero here but i do think you can change in when you craft a transaction object.
