### ISSUE TITLE
feat: add in `BlockType` enum for controlling block number during emulation

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#418]
# Idea
Updated from a comment below:

I think we should externalize this more and make it more than just an Option. Perhaps an enum for this along the lines of:
```rust
pub enum BlockType {
     UserControlled,
     RandomlySampled(f64, u32),
}
```
- `UserControlled`: will give the user the ability to make calls such as `client.mine_block()` and `client.set_block_timestamp()`.
- `Randomized(f64, u32)`: would give the user the the Poisson chosen block sizes with the block rate via the `f64` inner and we would let the block times update via the `u32` inner.
- `None`: The user would not update the blocks ever.

This `BlockType` can go into the `EnvironmentParameters`.

## Other details

We should probably try to implement this in some sort of RPC-like way such as listed in the [Anvil documentation](https://book.getfoundry.sh/reference/anvil/). For example, we can implement the request:
```
"evm_mine"
```
We should link this issue to #464.

Since blocks are not actually mined *per se*, we can maybe just implement a method on the `RevmMiddleware` such as `next_block` so that any clients may access this.

---
~~For those who will not need this feature, having the block number increment is just another chance for a bug a bit of overhead. Also, it relies on the user knowing what the block rate setting is doing.~~

~~- [ ] Add in an option for the `rate_parameter` when creating an environment.~~

**Comment by 0xJepsen** [comment]
I'll take this, and add it to #417

**Comment by Autoparallel** [comment]
I think we should externalize this more and make it more than just an Option. Perhaps an enum for this along the lines of:
```rust
pub enum BlockType {
     UserControlled,
     Randomized(f64),
     None,
}
```
- `UserControlled`: will give the user the ability to make calls such as `client.mine_block()` and `client.set_block_timestamp()`.
- `Randomized(f64, u32)`: would give the user the the Poisson chosen block sizes with the block rate via the `f64` inner and we would let the block times update via the `u32` inner.
- `None`: The user would not update the blocks ever.
