### ISSUE TITLE
feat: mutate database directly 

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#421]
The desired functionality here is an exposed API that bypasses the middleware to mutate the Ethereum database directly. 

The API should include
- Interface to load in main-net state to the DB.
- Manual way to set timestamp
- Manual way to increment / set the block number

This would enable forking main-net and a small set (Maybe just the above API exposed by the manager?) of utility features useful for robust analysis. @Alexangelj Let me know what you think about this feature set.

**Comment by Autoparallel** [comment]
I think we can add some of this with features in the middleware/rpc calls. I'll look into it. 

If so, we can externalize our block incrementing and give the user more flexibility in how they want to do it e.g., manually, not at all, or with Poisson.

**Comment by Autoparallel** [comment]
This is now fairly linked to other issues. E.g., #418, #464, #461. 

@0xJepsen @Alexangelj can you check out those issues and consider closing this one in favor for splitting up these tasks into smaller pieces?

**Comment by Alexangelj** [comment]
Yeah I think we close this one and tackle each requirement in separate issues.

My user stories I want:
- I want to move to any block.timestamp I want
- I want to have blocks be automatically mined on some interval in parallel to my agents running
- I want to be able to fetch state directly from the db for an account
- I want to write state directly to the db for an account

**Comment by Autoparallel** [comment]
@Alexangelj can you expand on the latter two and perhaps make issues for them if you think they aren't already made?

**Comment by Alexangelj** [comment]
> @Alexangelj can you expand on the latter two and perhaps make issues for them if you think they aren't already made?

https://github.com/primitivefinance/arbiter/issues/468

**Comment by Autoparallel** [comment]
Closed do to new issues.
