### ISSUE TITLE
feat: change `arbiter init` to call `arbiter bind` upon creation

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#428]
This is a small quality of life improvement that will eliminate requiring users to to generate bindings upon project initialization. This should touch the code in the binary. Specifically it should add a call to this function
https://github.com/primitivefinance/arbiter/blob/f10fee12b215a80968affa893f438953f7e5d890/bin/bind.rs#L19-L43

To the end of the initialization function here:
https://github.com/primitivefinance/arbiter/blob/f10fee12b215a80968affa893f438953f7e5d890/bin/init.rs#L29-L64

**Comment by 0xJepsen** [comment]
Reminder to edit the instructions in the read me when this change is made

**Comment by kinrezC** [comment]
I'm not entirely sure this would be a good change. It's unlikely that as a user I will want the bindings for e.g. `Counter.sol` to remain in the project once my development environment is setup. With that said, I think we should add an optional flag `-t` or `--template` at some point (similar to forge) to allow users to set up their project with different templates depending on use case.

**Comment by 0xJepsen** [comment]
> I'm not entirely sure this would be a good change. It's unlikely that as a user I will want the bindings for e.g. `Counter.sol` to remain in the project once my development environment is setup. With that said, I think we should add an optional flag `-t` or `--template` at some point (similar to forge) to allow users to set up their project with different templates depending on use case.

@Autoparallel, What are your thoughts? You suggested this feature.

**Comment by Autoparallel** [comment]
Couldn't they then just remove the contracts they don't want and `arbiter bind` again and be on with it?
