### ISSUE TITLE
chore: Alloy type migration in new revm release

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#435]
Revm recently bumped version to 3.1.1 and merged in their alloy migration. Would be good for us to propagate these changes downstream. The release notes can be found [here](https://github.com/bluealloy/revm/releases/tag/v22). To complete this we would bump the version of revm in our `cargo.toml`'s to 3.1.1 and make changes to use the alloy types where we have previously used revm or ethers types. This will ideally eliminate the need for utility functions like:
https://github.com/primitivefinance/arbiter/blob/f10fee12b215a80968affa893f438953f7e5d890/arbiter-core/src/environment.rs#L542-L555

When bumping the version there may be a collection of new compiler errors that will need to be addressed.

**Comment by Autoparallel** [comment]
Can you give a bit more detail as far as what this will entail?

**Comment by 0xJepsen** [comment]
So looking more into this there is nothing we need to do to incorporate this. all the types are correctly used under the hood.

**Comment by 0xJepsen** [comment]
Going to close
