### ISSUE TITLE
bug: `arbiter bind` should generate bindings for contract dependencies

### ISSUE THREAD

**Issue by kinrezC** [primitivefinance/arbiter#439]
### Description
`arbiter bind` will only generate bindings for contracts inside the `contracts` directory.

### Steps to reproduce
1. `arbiter init test-project && cd test-project`
2. `forge install primitivefinance/portfolio` (this will create a submodule in the `lib` directory)
3. `arbiter bind`

### Expected Behavior
The portfolio bindings are generated in `src/bindings`.

### What actually happens
Bindings are only generated for the `std-*.sol` and `Counter.sol` contracts, but not for `lib/portfolio`.

**Comment by Autoparallel** [comment]
As an add-on, I think it would be nice to specify which specific contracts you want to have bindings generated for (if you want). Having extraneous contracts is a bit of a headache sometimes. We could do this with some type of config file or even add it to a Foundry.toml.
