### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by ts0yu** [primitivefinance/arbiter#45]
Currently we are using `unwrap()` to handle most errors but it would be nice to have some internal error representation using the `thiserror` crate.

**Comment by Autoparallel** [comment]
This is a LARGE issue. Can we break it up into smaller tasks such as #71 ?

**Comment by ts0yu** [comment]
for sure @Autoparallel

**Comment by Autoparallel** [comment]
@ts0yu can you make milestones?

**Comment by eljhfx** [comment]
^ We should close this one out and break it up. I know we need to add custom errors for invalid config files submitted through the command line, would be nice to keep a running list of others.

@Autoparallel @ts0yu

**Comment by ts0yu** [comment]
I added custom errors to the config module already

**Comment by 0xJepsen** [comment]
Closing for beta release
