### ISSUE TITLE
feat: add ability to write the EVM database to disk for post-processing

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#455]
# Idea
If we can write the EVM database to disk, then we are free to use tools like [`cryo`](https://github.com/paradigmxyz/cryo) to analysis the data and post-process it. This can streamline the process so that users don't have to capture the data they want on the fly -- rather they capture the whole set of state transitions and diffs.

**Is your feature request related to a problem? Please describe.**
We need the ability to provide users a clear way to process the data they get in simulations.

## Solution
The potential solution here is to change the DB that we are using. As was suggested by Dragan (creator/maintainer of [`revm`](https://github.com/bluealloy/revm), we could use an [alternative DB]( https://github.com/bluealloy/revm/blob/3907fdf9a8a7db05b058765563105b09df908c82/crates/revm/src/db/states/state_builder.rs#L8). I need to look into how exactly we implement this, get it in, test it out, and add functionality to write the database to disk.

## Alternative approaches
Other approaches could use other DB's but this was suggested by the legend himself. We could also add other functionality to selectively save data in a CSV, but that seems less modular.

**Comment by Autoparallel** [comment]
We should push something like this in v0.5.0 so I am marking it as such.

**Comment by 0xJepsen** [comment]
Solved in a different way
