### ISSUE TITLE
feat: directly overwriting database

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/arbiter#468]
# Idea
Given an account (i.e. a smart contract deployed), enable me to write directly to its state in the underlying database.

## Solution

For example, my contract:

```
contract OverwriteMe {

  mapping(address => uint) public balanceOf;

  function addBalance(address target, uint amount) public {
    balanceOf[target] = amount;
  }

}
```

Instead of calling `addBalance` on the contract, I want to directly change the state of the contract's mapping for the `target` address to a desired `amount`.

## Alternative approaches
Provide a clear and concise description of any alternative solutions or features you've considered for this feature here.

**Comment by Autoparallel** [comment]
@Alexangelj are cheatcodes good enough for this? Or do we want even more control? Just trying to figure out how the API will work here!

**Comment by Alexangelj** [comment]
The cheatcodes I use in foundry are vm.store, which writes to a storage slot. If we can get that it would be sufficient
