### ISSUE TITLE
feat: `arbiter-core` API upgrades

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#481]
# Idea
There are a few places in the `arbiter-core` end user API that could be tidied up and made easier. For instance:
- [x] Make a `EnvironmentParameters::new()` function that takes an `impl Into<String>`. Possibly use the builder pattern.
- [ ] Look for anywhere where we consistently have to cast to another type prior to a call in [`portfolio_simulations`](https://github.com/primitivefinance/portfolio_simulations).

**Is your feature request related to a problem? Please describe.**
Want to make the user API as easy as possible.

**Comment by Autoparallel** [comment]
@kinrezC do you want to try to do some of this in #513 since it is a larger refactor anyway?

**Comment by Autoparallel** [comment]
Leaving this to your discretion!

**Comment by kinrezC** [comment]
> Make a EnvironmentParameters::new() function that takes an impl Into<String>. Possibly use the builder pattern.

This is already done in #513
