### ISSUE TITLE
feat: Nonce Manager

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#484]
# Idea

We ought to be incrementing the nonces for all accounts as they submit transactions as they prevent replay attacks that we don't want to come up in discovering emergent behavior. 

## Solution

There is a none manager trait that is generic over some middleware [here](https://github.com/gakonst/ethers-rs/blob/master/ethers-middleware/src/nonce_manager.rs) I think this is the correct approach to move forward with. 

## Alternative approaches
We may also be able to make a naive nonce manager if we so desire.

**Comment by Autoparallel** [comment]
@0xJepsen do you want to take this issue?
