### ISSUE TITLE
feat(arbiter-bin): create a project that is **not** a git repo

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#502]
# Idea
If a user wants to create a new Arbiter project inside of their current smart contract repository, it may not be great to give them another whole git repository inside of it. Having a flag to disable git would be nice so you could do 
```sh
arbiter init my_project --no-git
```

**Is your feature request related to a problem? Please describe.**
Yes, we have been given a little bit of grief that this makes the project a submodule and is annoying!

## Solution
We can even just remove the `.git` directory if we would like when we clone the template.

## Alternative approaches
Don't clone and don't use `cargo new` either.

**Comment by 0xJepsen** [comment]
Wouldn't cargo new be a good approach for this?
