### ISSUE TITLE
feat(contracts): handle approvals in `LiquidExchange` and in `ArbiterToken`

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#508]
# Idea
We need to do token transfer approvals in the `LiquidExchange` so that a user doesn't ever have to do them externally with the contract. Also, we can add a `approve_and_transfer` function to `ArbiterToken` to streamline the process for this if we ever need to transfer token between clients.

**Is your feature request related to a problem? Please describe.**
Yes this was annoying UX!

## Solution
- [ ] Transfer approvals in `LiquidExchange`.
- [ ] Add a `approve_and_transfer` function for `ArbiterToken`.

**Comment by 0xJepsen** [comment]
no longer relevant
