### ISSUE TITLE
feat: remove `Manager` and use builder pattern for `Environment`

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#513]
# Idea

Mentioned by @kinrezC earlier in team chat. I think the UX for this could be better by using something like

```rust
let env = Environment::new().block_settings(some_settings).gas_settings(other_settings).label("label".into()).start()?;
```

## Solution

Remove constructor parameters from the environment constructor and build the setters. 

## Things to consider

What should the behavior be when someone attempts to start the `env` when not gas / block / label, are not set?

edit by @kinrezC 
Tasks included in this issue:
1. Remove `manager`, sims will now be created and run via the creation of an `Environment`. 
2. Add defaults for `Environment::{BlockSettings, GasSettings}` to be `UserControlled`
3. Make `Environment::label` optional for tagging on concurrent sims
4. Refactor `Environment` to use builder pattern for modifying settings and adding a label

**Comment by Autoparallel** [comment]
Re: we can just default the values when they're not set. A `None` just means `UserControlled`

**Comment by Autoparallel** [comment]
@kinrezC can you add to this issue from #512 and give a list of tasks you plan on doing?

**Comment by kinrezC** [comment]
New `environment` creation via `EnvironmentBuilder`:

```rust
// Basic environment
// default block_settings: BlockSettings::UserControlled
// default gas_settings: GasSettings::UserControlled
// default label: None
let environment = EnvironmentBuilder::new().build();
// Custom environment
let environment = EnvironmentBuilder::new()
.block_settings(BlockSettings::RandomlySampled {
  block_rate: 12,
  block_time: 1,
  seed: 1,
})
.gas_settings(GasSettings::RandomlySampled { multiplier: 1})
.label("stuff".into());
```
