### ISSUE TITLE
:memo: Docs: (subsection)  CLI  installing with cargo and starting with `arbiter init` using `arbiter bind` submodules etc

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#557]
This should add sufficient documentation to the installation section of the #538. It should cover installing arbiter with cargo, using `arbiter init` and `arbiter bind`, as well as using submodules with `forge install`

**Comment by ruvaag** [comment]
I can start with this

**Comment by 0xJepsen** [comment]
Great! I assigned to you!
