### ISSUE TITLE
feat: Autostart the environment upon creation. 

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#560]
# Idea

Currently when building a simulation we have the end user start the environment after they create it 
```rust
    let mut manager = Manager::new();
    let _ = manager.add_environment(EnvironmentParameters {
        label: TEST_ENV_LABEL.to_owned(),
        block_settings: BlockSettings::UserControlled,
        gas_settings: GasSettings::UserControlled,
    });
    manager.start_environment(TEST_ENV_LABEL)?;
 ```
# Solution 
We should auto start the environment when we create it to simplify end user API

**Comment by kinrezC** [comment]
This api is outdated after #513.  I don't think we can do this with the builder pattern because if it started on `new` we wouldn't be able to have optional builder params.

**Comment by 0xJepsen** [comment]
> What we can do is have the current `build` just be `run` instead. Instead of returning `Environment::new()` in `build` on the builder that should just run the environment?

Yeah what i ended up doing to work with this is just have the `.build()` method start the env
