### ISSUE TITLE
Chore: bump minor versions on dependancies

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#591]
We want to get some downstream minor patches propagated into the repo the most exiting of which is the allow primitives from revm here [#revm](https://github.com/primitivefinance/arbiter/pull/589)

We may want to do this in the feature branch in case it causes a breaking change, but if it doesn't i am open to merging it into main as a patch.

**Comment by ruvaag** [comment]
I can take this up

**Comment by 0xJepsen** [comment]
Assigned to You!
