### ISSUE TITLE
repo(ci): add `cargo +nightly udeps` check to CI/CD

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#608]
# Idea
It would be good to ensure we don't ever carry around extra dependencies. We can run a `cargo +nightly udeps` check for all the crates and features. This should fail CI/CD if there is any unused dependency found.

**Comment by 0xJepsen** [comment]
Ran into this uncaught exception: https://github.com/est31/cargo-udeps/issues/218

**Comment by 0xJepsen** [comment]
Found out this is an upstream issue on MacOS Sonoma and curl 
https://github.com/alexcrichton/curl-rust/issues/524#issuecomment-1753070751
looks like it's fixed for rust version 1.71 so will make a new workflow that uses that version (I think stable is 1.73 now)
