### ISSUE TITLE
Realtime Price Plotting

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#62]
Since we have a `plotly` set up to plot the GBM price paths, we could also use it to plot Uniswap prices instead or on top of the CLI output. [Here's the rough idea (in python `plotly`)](https://community.plotly.com/t/plot-real-time-data/31467).

**Comment by eljhfx** [comment]
This is a really cool idea. Would be down to take this one but not sure how much of a priority it is right now

**Comment by Autoparallel** [comment]
@eljhfx this is the kind of fun issue you should attack if you feel like you want to up that sweet sweet UI/UX feel.

**Comment by 0xJepsen** [comment]
Would be nice if we write this as a helper and call it in the `monitor_pool` method in the uniswap crate

**Comment by Autoparallel** [comment]
Close as stale. We can readdress this later with our own visualization package (in the works).
