### ISSUE TITLE
feat(arbiter-core): create middleware from forked EOA

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#624]
# Idea
We can now fork EOAs into Arbiter environments, but we have no easy way to give them middleware. So we need to do that.

## Solution
We can make a new function for `RevmMiddleware` like so:
```rust
impl RevmMiddleware {
  fn new_from_address(env: Environment, address: Address, label: Option<&str>) ->  Self {
      ...
  }
// ~ snip
```
The method body can follow a lot of the `RevmMiddleware::new()` we already have. The only difference is we won't create a wallet with a private key. Perhaps this means we should redesign some of the structure here a bit making wallets optional and addresses required. 

## Alternative approaches
We could create a whole different middleware for them too. I'm open to other suggestions.

**Comment by 0xJepsen** [comment]
I like the design approach you're cooking on here. I'm down to cook on this tomorrow.
