### ISSUE TITLE
Flamegraph

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#647]
# Idea
Add a flamegraph for the repository so and show on readme.

**Comment by Autoparallel** [comment]
You can flamegraph the arbiter part of the bench code. I did that before.

**Comment by Autoparallel** [comment]
@0xJepsen let's do this soon or just drop it. But this is getting quite stale!

**Comment by 0xJepsen** [comment]
i feel like it's not a priority right now
