### ISSUE TITLE
Adding error handling when Cli input is invalid

### ISSUE THREAD

**Issue by eljhfx** [primitivefinance/arbiter#71]
When Cli inputs are spelled wrong, the code is panicking.

"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/elijahfox/Desktop/arbiter/crates/clairvoyance/src/uniswap.rs:192:37`"

We should add error handling with print statements to explain what's going on.

**Comment by eljhfx** [comment]
@Autoparallel @0xJepsen 

Happy to take this one

**Comment by ts0yu** [comment]
it's part of the more general error enumeration issue. we should discuss how to represent these internally

**Comment by eljhfx** [comment]
What do you mean by this @ts0yu

**Comment by eljhfx** [comment]
Are you suggesting it's included in #45 ? Can close it if yeah

**Comment by Autoparallel** [comment]
@eljhfx It isn't mentioned directly in there. Your issue here sounds more tractable as it is smaller. The error handling should almost be a milestone as there are places to do it throughout the codebase.

**Comment by eljhfx** [comment]
@Autoparallel If you want to assign this to me it probably shouldnt take more than a day or two

**Comment by Autoparallel** [comment]
@eljhfx you have been assigned.

May the force be with you
