### ISSUE TITLE
Substitute ERC20 contracts in place of Hello World!

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/arbiter#84]
A better basic contract to start off with is ERC20. We will need to utilize ERC20 in nearly all simulations anyway. These contracts will have read and write capabilities. 

In this issue, let's get rid of Hello World! and deploy ERC20 as well. To close this issue, the update should involve reading from ERC20.

**Comment by Autoparallel** [comment]
@0xJepsen Should we make an issue for deploying UniV3 factory first?

**Comment by Autoparallel** [comment]
@0xJepsen @kinrezC after discussion I am changing this issue to the closest relevant one.

**Comment by Autoparallel** [comment]
This is high priority!
