### ISSUE TITLE
refactor(arbiter-core): `data_collection.rs` -> `events.rs`

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/arbiter#840]
# Idea
The `data_collection.rs` module has grown in scope and has become a bit of a beast. Not to mention, it's just not aptly named anymore. I propose renaming the module to `events.rs` and renaming `EventLogger` to something else.

There are two key features we have here. At the core, we could use the generalized event streamer we have in place to feed into file output if we want, or just have that stream returned to the caller. We just want to have access to (possibly combined) streams of events  and access to file out of whatever events we set. 

We can discuss more.

**Comment by 0xJepsen** [comment]
Maybe we can put polars behind a feature flag since it is only conditionally used for CSV and Parquet
