### ISSUE TITLE
simulation struct

### ISSUE THREAD

**Issue by ts0yu** [primitivefinance/arbiter#90]
create a robust struct for all our simulation related needs:
- executing transactions
- fetching storage slots
- inserting contracts and accounts

should fit nicely w/ `architect` 

links to : https://github.com/primitivefinance/arbiter/issues/84

**Comment by ts0yu** [comment]
i will work on this.

**Comment by Autoparallel** [comment]
@ts0yu see what you think of the start to the `testbed` module. It will definitely see changes and I am open to modifying structures further.

**Comment by ts0yu** [comment]
had a look - looks good so far. I'll work on building off of that @Autoparallel

**Comment by Autoparallel** [comment]
@ts0yu, great. We'll have a much clearer idea on all of it as revm is fully implemented for sims.

**Comment by ts0yu** [comment]
I would say so, yeah

**Comment by 0xJepsen** [comment]
I think @kinrezC is also working on some feature for the module as well

**Comment by ts0yu** [comment]
what is he working on?
